fixed store response schema

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,8 +1,15 @@
-FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
+FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.tsx?$' | sed 's| |\\ |g')
 [ -z "$FILES" ] && exit 0
 
 # Prettify all selected files
-echo "$FILES" | xargs ./node_modules/.bin/eslint
+eslint_output=$(echo "$FILES" | xargs ./node_modules/.bin/eslint)
+
+# Check if ESLint failed
+if [ $? -ne 0 ]; then
+    echo "ESLint failed. Commit aborted."
+    echo "$eslint_output"
+    exit 1
+fi
 
 # Add back the modified/prettified files to staging
 echo "$FILES" | xargs git add
@@ -11,6 +18,7 @@ sudo docker-compose build test postgres
 
 # Run tests
 docker-compose up --abort-on-container-exit test postgres 
+test_status=$?
 
 # Stop and remove containers
 docker-compose down
@@ -21,4 +29,4 @@ if [ $test_status -ne 0 ]; then
 fi
 
 exit 0
-#
+
